### ISSUE TITLE
Figure out Raspi-I2C root

### ISSUE THREAD

**Issue by hxlnt** [nebrius/johnny-five-iot-edge#7]
Done: Not sure; needs more information.

**Comment by toolboc** [comment]
i2c is made available to the module via the device parameters passed to the "Container Create Options":

            "Devices": [
                {
                    "PathOnHost": "/dev/i2c-1",
                    "PathInContainer": "/dev/i2c-1",
                    "CgroupPermissions": "rwm"
                },
                {
                    "PathOnHost": "/dev/gpiomem",
                    "PathInContainer": "/dev/gpiomem",
                    "CgroupPermissions": "rwm"
                }
            ],
